
# Delete subspecies in pyPHLAWD tree

#Charadrii <- drop.tip(Charadrii, tip=c(
"Larus_cachinnans_cachinnans",
"Larus_mongolicus_mongolicus",
"Larus_argentatus_argentatus",
"Larus_michahellis_michahellis",
"Larus_michahellis_atlantis",
"Larus_heuglini_taimyrensis",
"Larus_glaucoides_kumlieni",
"Larus_fuscus_intermedius",
"Larus_fuscus_graellsii",
"Larus_fuscus_fuscus",
"Larus_vegae_birulae",
"Larus_cachinnans_barabensis",
"Larus_argentatus_omissus",
"Larus_argentatus_argenteus",
"Larus_dominicanus_judithae",
"Larus_dominicanus_vetula",
"Larus_occidentalis_wymani",
"Larus_occidentalis_occidentalis",
"Larus_glaucoides_glaucoides",
"Larus_canus_kamtschatschensis",
"Larus_canus_canus",
"Larus_canus_heinei",
"Gygis_alba_microrhyncha",
"Gygis_alba_pacifica",
"Gygis_alba_candida",
"Gygis_alba_rothschildi",
"Thalasseus_sandvicensis_acuflavidus",
"Thalasseus_sandvicensis_sandvicensis",
"Thalasseus_bengalensis_bengalensis",
"Thalasseus_bengalensis_emigratus",
"Thalasseus_maximus_albididorsalis",
"Thalasseus_maximus_maximus",
"Sternula_albifrons_albifrons",
"Alle_alle_polaris",
"Alle_alle_alle",
"Uria_lomvia_lomvia",
"Uria_aalge_inornata",
"Uria_aalge_aalge",
"Uria_aalge_albionis",
"Cepphus_columba_eureka",
"Cepphus_columba_adianta",
"Cepphus_columba_columba",
"Cepphus_grylle_ultimus",
"Cepphus_grylle_arcticus",
"Cepphus_grylle_islandicus",
"Cepphus_grylle_mandtii",
"Cepphus_grylle_grylle",
"Fratercula_arctica_grabae",
"Haematopus_ostralegus_ostralegus",
"Pluvialis_squatarola_squatarola",
"Numenius_phaeopus_variegatus",
"Numenius_arquata_arquata",
"Limosa_limosa_melanuroides",
"Limosa_limosa_islandica",
"Limosa_limosa_limosa",
"Limosa_lapponica_taymyrensis",
"Limosa_lapponica_lapponica",
"Gallinago_gallinago_faeroeensis",
"Gallinago_gallinago_gallinago",
"Coenocorypha_aucklandica_meinertzhagenae",
"Coenocorypha_aucklandica_aucklandica",
"Brachyramphus_marmoratus_marmoratus"
))


# Delete outlier

Charadrii <- drop.tip(Charadrii, tip="Turnix_hottentotta")
